platform :ios, '15.0'

install! 'cocoapods', :warn_for_unused_master_specs_repo => false
source 'https://cdn.cocoapods.org/'

use_frameworks!

def pods
  pod 'AlamofireImage'
  pod 'TagTextView', :path => '../'
end
 
target 'TagTextViewExample' do
    pods
end
